export const ProjectsData = [
  {
    id: 1,
    title: "College Website",
    description: "College Website using HTML, CSS",
    url: "https://arungovil.github.io/CollegeWebsite/",
    icon: "CgWebsite",
  },
  {
    id: 2,
    title: "BloodHub",
    description: "Realtime blood bank mobile app",
    url: "https://arungovil.github.io/BloodHub/",
    icon: "CiHeart",
  },
  {
    id: 3,
    title: "NotesApp",
    description: "Note sharing app for classroom",
    url: "https://github.com/ArunGovil/NotesApp",
    icon: "CiStickyNote",
  },
  {
    id: 4,
    title: "ShareNotes",
    description: "Note sharing app for College",
    url: "https://arungovil.github.io/ShareNotes/",
    icon: "CiShare2",
  },
  {
    id: 5,
    title: "Product Landing Page",
    description: "Demo Product Landing Page",
    url: "  https://github.com/ArunGovil/ProductPage",
    icon: "TbBrandProducthunt",
  },
  {
    id: 6,
    title: "Multi Step Form",
    description: "React stepper form component",
    url: "https://github.com/ArunGovil/StepForm",
    icon: "BsBarChartSteps",
  },
  {
    id: 7,
    title: "Dawkins Scale",
    description: "Dawkins scale of faith visualized",
    url: "https://dawkins.netlify.app",
    icon: "GiThermometerScale",
  },
  {
    id: 8,
    title: "Personal Website",
    description: "Dawkins scale of faith visualized",
    url: "https://arungovil.me",
    icon: "RxPerson",
  },
  {
    id: 9,
    title: "cmdr",
    description: "One stop commands directory",
    url: "https://github.com/ArunGovil/cmdr",
    icon: "BsTerminal",
  },
];
